DROP TABLE IF EXISTS sys_user_permission;
DROP TABLE IF EXISTS sys_role_permission;
DROP TABLE IF EXISTS sys_permission;
DROP TABLE IF EXISTS operation_audit_log;
DROP TABLE IF EXISTS payment_record;
DROP TABLE IF EXISTS service_order;
DROP TABLE IF EXISTS appointment_item;
DROP TABLE IF EXISTS appointment;
DROP TABLE IF EXISTS service_project_inventory;
DROP TABLE IF EXISTS inventory_stock_log;
DROP TABLE IF EXISTS inventory_sku;
DROP TABLE IF EXISTS service_project;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS staff_member;

CREATE TABLE staff_member (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50),
    phone VARCHAR(20),
    gender INT,
    position VARCHAR(50),
    status INT,
    remark VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_user (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role_id INT NOT NULL,
    staff_id BIGINT,
    status INT NOT NULL,
    last_login_time TIMESTAMP,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE inventory_sku (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    category VARCHAR(50),
    unit VARCHAR(20),
    quantity DECIMAL(12,2),
    safety_stock DECIMAL(12,2),
    cost_price DECIMAL(12,2),
    supplier VARCHAR(100),
    status INT,
    remark VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE inventory_stock_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT,
    change_type VARCHAR(30),
    change_quantity DECIMAL(12,2),
    before_quantity DECIMAL(12,2),
    after_quantity DECIMAL(12,2),
    related_order_id BIGINT,
    operator_id BIGINT,
    remark VARCHAR(255),
    create_time TIMESTAMP
);

CREATE TABLE appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_no VARCHAR(64) UNIQUE,
    customer_id BIGINT,
    staff_id BIGINT,
    appointment_time TIMESTAMP,
    status INT,
    total_duration_minutes INT,
    remark VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE TABLE appointment_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT,
    service_project_id BIGINT,
    staff_id BIGINT,
    service_name VARCHAR(100),
    price DECIMAL(12,2),
    duration_minutes INT,
    sort_no INT,
    create_time TIMESTAMP
);

CREATE TABLE service_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) UNIQUE,
    request_id VARCHAR(36) UNIQUE,
    appointment_id BIGINT UNIQUE,
    customer_id BIGINT,
    order_type VARCHAR(20),
    original_amount DECIMAL(12,2),
    discount_amount DECIMAL(12,2),
    receivable_amount DECIMAL(12,2),
    paid_amount DECIMAL(12,2),
    debt_amount DECIMAL(12,2),
    debt_status INT,
    pay_status INT,
    order_status INT,
    remark VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    deleted INT DEFAULT 0
);

CREATE TABLE payment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    payment_no VARCHAR(64) UNIQUE,
    payment_method VARCHAR(20),
    pay_amount DECIMAL(12,2),
    pay_status INT,
    pay_time TIMESTAMP,
    operator_id BIGINT,
    remark VARCHAR(255),
    create_time TIMESTAMP
);

CREATE TABLE service_project (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    category VARCHAR(50),
    price DECIMAL(12,2),
    duration_minutes INT,
    description VARCHAR(255),
    status INT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE service_project_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_project_id BIGINT,
    inventory_id BIGINT,
    consume_quantity DECIMAL(12,2),
    status INT,
    remark VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_permission (
    id BIGINT PRIMARY KEY,
    permission_code VARCHAR(100) NOT NULL,
    permission_name VARCHAR(100) NOT NULL,
    permission_group VARCHAR(50) NOT NULL,
    method VARCHAR(10),
    path_pattern VARCHAR(200),
    menu_path VARCHAR(100),
    action_key VARCHAR(100),
    status INT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INT NOT NULL,
    permission_id BIGINT NOT NULL,
    create_time TIMESTAMP
);

CREATE TABLE sys_user_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    create_time TIMESTAMP,
    UNIQUE (user_id, permission_id)
);

CREATE TABLE operation_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_user_id BIGINT,
    operator_staff_id BIGINT,
    action_type VARCHAR(64),
    target_type VARCHAR(64),
    target_id BIGINT,
    detail VARCHAR(500),
    create_time TIMESTAMP
);
