DROP TABLE IF EXISTS sys_user_permission;
DROP TABLE IF EXISTS sys_role_permission;
DROP TABLE IF EXISTS sys_permission;
DROP TABLE IF EXISTS inventory_stock_log;
DROP TABLE IF EXISTS inventory_sku;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS staff_member;

CREATE TABLE staff_member (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50),
    phone VARCHAR(20),
    gender INT,
    position VARCHAR(50),
    status INT,
    remark VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_user (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role_id INT NOT NULL,
    staff_id BIGINT,
    status INT NOT NULL,
    last_login_time TIMESTAMP,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE inventory_sku (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    category VARCHAR(50),
    unit VARCHAR(20),
    quantity DECIMAL(12,2),
    safety_stock DECIMAL(12,2),
    cost_price DECIMAL(12,2),
    supplier VARCHAR(100),
    status INT,
    remark VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE inventory_stock_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT,
    change_type VARCHAR(30),
    change_quantity DECIMAL(12,2),
    before_quantity DECIMAL(12,2),
    after_quantity DECIMAL(12,2),
    related_order_id BIGINT,
    operator_id BIGINT,
    remark VARCHAR(255),
    create_time TIMESTAMP
);

CREATE TABLE sys_permission (
    id BIGINT PRIMARY KEY,
    permission_code VARCHAR(100) NOT NULL,
    permission_name VARCHAR(100) NOT NULL,
    permission_group VARCHAR(50) NOT NULL,
    method VARCHAR(10),
    path_pattern VARCHAR(200),
    menu_path VARCHAR(100),
    action_key VARCHAR(100),
    status INT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INT NOT NULL,
    permission_id BIGINT NOT NULL,
    create_time TIMESTAMP
);

CREATE TABLE sys_user_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    create_time TIMESTAMP
);
